force-app/main/default/objects/Get_Address_IO__c/fields/postcodeLength__c.field-meta.xml
<CustomField>
    <fullName>postcodeLength__c</fullName>
    <label>postcodeLength</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GetAddressIoConnectSettings.cls
public with sharing class GetAddressIoConnectSettings {

    @AuraEnabled(cacheable=true)
    public static String getApiKey(){

        Get_Address_IO__c apiKeySetting = Get_Address_IO__c.getInstance('api-key');
        return String.valueOf(apiKeySetting.apiKey__c);
      
    }

    @AuraEnabled(cacheable=true)
    public static Integer getPostCodeLength(){

        Get_Address_IO__c postcodeSetting = Get_Address_IO__c.getInstance('api-key');
        return Integer.valueOf(postcodeSetting.postcodeLength__c);
      
    }

}